add styling to transport page
chuckeles/elder-assistant pull request #6
Opened 2016-11-11 15:20 UTC by brando

neviem ako pridat <i class="fa fa-check"></i> ku tlacidlu "Potvrdit" lebo je to ako <input>

2016-11-11 16:22 UTC, chuckeles commented
Pozeral si Bootstrap?

https://v4-alpha.getbootstrap.com/components/buttons/

2016-11-11 16:23 UTC, chuckeles commented
Možeš sa inšpirovať ostatnými stránkami, ktoré sú už spravené. Ale vôbec neviem, že čo sa pýtaš 😃 ...

2016-11-11 16:24 UTC, martindzejky requested changes
Je to pokrok, ale zvyšok codebase používa 4 medzery na odsadzovanie. Mohol som to niekde aj spomenúť, prepáč. Mohol by si to opraviť?

2016-11-11 16:26 UTC, chuckeles commented on transport.html
> +            	<i class="fa fa-times"></i>
Tu máš odsadenie úplne odveci 😅

2016-11-12 10:20 UTC, martindzejky approved these changes
Vieš čo, indentation máš stále v prdeli, ale kašlať na to 😆 .

ok. no neviem robim do to v sublime text editore a snazil som sa to tam upravit (som myslel ze si narazal tam na tych paru riadkov, ale asi nie :)  ), v pondelok to doriesime

2016-11-12 10:21 UTC, merged

2016-11-12 17:43 UTC, brando commented
@chuckeles ja som chcel este pokracovat  na tej transport-page ;)

2016-11-12 19:35 UTC, chuckeles commented
@brando pokračuj 👍 sprav si ďalšiu branch a ideš